site_name: Docs Common
repo_url: https://github.com/vicmil-work/docs_common
repo_name: vicmil-work/docs_common

theme:
  name: material

  features:
    - content.code.copy

  palette:
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Python Setup: python_setup.md
  - Python MKDocs: python_docs.md
  - C++ Standard library: cpp_std.md
  - C++ Image using stb : cpp_image.md
  - C++ Graphics using OpenGL : cpp_opengl.md
  - Git commands: git_commands.md
  - Server: server_setup.md
  - VSCode Setup: vscode_setup.md
markdown_extensions:
  - codehilite:
      guess_lang: false  # Ensures correct language highlighting
  - fenced_code
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
